"""remove sujectives from cigars models

Revision ID: ece48e79bfcc
Revises: 41e292b9a027
Create Date: 2024-06-23 19:42:51.096038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece48e79bfcc'
down_revision: Union[str, None] = '41e292b9a027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cigars', 'rating')
    op.drop_column('cigars', 'flavor_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cigars', sa.Column('flavor_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cigars', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
